include:
  - project: devops/gitlab-ci
    file: docker-v2.yml

variables:
  REPO_NAME: "bw-superset"
  GOOGLE_PREFIX: "europe-docker.pkg.dev/brightwrite-211800/bw-docker"
  NEXUS_PREFIX: "nexus.xcover.covergenius.biz/infrastructure"
  IMAGE_NAME: "bw-superset"
  DOCKER_RELEASE_TAG: "${CI_COMMIT_REF_NAME}__${CI_COMMIT_SHORT_SHA}"
  NEXUS_IMAGE_NAME: "${NEXUS_PREFIX}/${IMAGE_NAME}:${DOCKER_RELEASE_TAG}"

stages:
  - build
  - sync_cdn

.login_to_gcp: &login_to_gcp
  - gcloud iam workload-identity-pools create-cred-config
    projects/197906452930/locations/global/workloadIdentityPools/aws-pool/providers/aws-provider
    --service-account=gitlab-ci-sa@brightwrite-211800.iam.gserviceaccount.com
    --enable-imdsv2
    --output-file=.gcp_temp_cred.json
    --aws
  - gcloud config set project brightwrite-211800
  - export GOOGLE_APPLICATION_CREDENTIALS=`pwd`/.gcp_temp_cred.json
  - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json

.docker_login: &docker_login
  - docker login -u "${NEXUS_USERNAME}" -p "${NEXUS_PASSWORD}" "${NEXUS_HOST}"

build_superset:
  stage: build
  image: google/cloud-sdk:alpine
  services:
    - name: docker:23-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - *docker_login
    - *login_to_gcp
    - gcloud auth configure-docker -q europe-docker.pkg.dev
  script:
    - >
      docker build --build-arg="ASSET_BASE_URL=${ASSET_BASE_URL}"
      --build-arg="CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}" 
      --build-arg="BW_PUBLIC_KEY=${BW_PUBLIC_KEY}" 
      --build-arg="BW_APP_ID=${BW_APP_ID}" -t ${NEXUS_IMAGE_NAME} . ;
      docker tag "${NEXUS_IMAGE_NAME}" "${GOOGLE_PREFIX}/${IMAGE_NAME}:${DOCKER_RELEASE_TAG}";
      docker tag "${NEXUS_IMAGE_NAME}" "${GOOGLE_PREFIX}/${IMAGE_NAME}:latest";
      docker tag "${NEXUS_IMAGE_NAME}" "${GOOGLE_PREFIX}/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}";
      docker push ${NEXUS_IMAGE_NAME};
      docker push --all-tags "${GOOGLE_PREFIX}/${IMAGE_NAME}";
  rules:
    - if: $CI_COMMIT_BRANCH
      variables:
        ASSET_BASE_URL: "https://cdn.brightwrite-staging.com"
        BW_PUBLIC_KEY: "a02b211d9dbb71b299b980b16593ed22"
        BW_APP_ID: "superset_staging"
    - if: $CI_COMMIT_TAG == "production"
      variables:
        ASSET_BASE_URL: "https://cdn.brightwrite.com"
        BW_PUBLIC_KEY: "031b7df8719e4205cd29232e0b34b69c"
        BW_APP_ID: "superset_production"

sync_CDN_stag:
  stage: sync_cdn
  image: google/cloud-sdk:alpine
  variables:
    CDN_BUCKET: "cdn.brightwrite-staging.com"
  services:
    - name: docker:23-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - *docker_login
    - *login_to_gcp
    - gcloud auth configure-docker -q europe-docker.pkg.dev
  script:
    - mkdir static
    - docker pull "${GOOGLE_PREFIX}/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker run -d -v ./static/:/superset/static "${GOOGLE_PREFIX}/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker cp $(docker ps -lq):/app/superset/static/ ./
    - gsutil rsync -cr ./static "gs://${CDN_BUCKET}/superset/${CI_COMMIT_SHORT_SHA}/static"
  rules:
    - if: $CI_COMMIT_BRANCH

sync_CDN_prod:
  stage: sync_cdn
  image: google/cloud-sdk:alpine
  variables:
    CDN_BUCKET: "bw-event-public"
  services:
    - name: docker:23-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - *docker_login
    - *login_to_gcp
    - gcloud auth configure-docker -q europe-docker.pkg.dev
  script:
    - mkdir static
    - docker pull "${GOOGLE_PREFIX}/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker run -d -v ./static/:/superset/static "${GOOGLE_PREFIX}/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker cp $(docker ps -lq):/app/superset/static/ ./
    - gsutil rsync -cr ./static "gs://${CDN_BUCKET}/superset/${CI_COMMIT_SHORT_SHA}/static"
  rules:
    - if: $CI_COMMIT_TAG == "production"
  environment:
    name: production
